config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  concern :votable do
    member do
      patch :vote_yes
      patch :vote_no
    end
  end

  concern :commentable do
    resources :comments, only: [:create]
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, shallow: true, except: :index, concerns: [:votable, :commentable] do
      member do
        patch :mark_as_best
      end
    end

    resources :subscriptions, only: [:create]
  end

  resources :attachments,   only: [:destroy]
  resources :links,         only: [:destroy]
  resources :rewards,       only: [:index]
  resources :votes,         only: [:destroy]
  resources :subscriptions, only: [:destroy]

  resources :authorizations, only: [:create] do
    member do
      get :confirm_email
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, only: [:index, :show, :create, :update, :destroy], shallow: true
      end
    end
  end

  get '/search', to: 'search#search'

  mount ActionCable.server => '/cable'

  root to: 'questions#index'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable
  
  belongs_to :user

  has_one :reward, dependent: :destroy
  has_many :answers, -> { order(best: :desc, created_at: :desc) }, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy
  
  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :subscribe_the_author

  private

  def subscribe_the_author
    subscriptions.create!(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: [:show, :update, :destroy]

  authorize_resource
  
  def index
    @questions = Question.all.sort
    render json: @questions, each_serializer: QuestionsSerializer
  end

  def show
    render json: @question
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_resource_owner
    
    if @question.save
      head :ok
    else
      head :unprocessable_entity
    end
  end

  def update
    if @question.update(question_params)
      head :ok
    else
      head :unprocessable_entity
    end
  end

  def destroy
    @question.destroy
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, links_attributes: [:name, :url])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :update, :destroy]

  after_action :publish_question, only: [:create]

  authorize_resource
  
  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answer.links.new

    if user_signed_in?
      @subscription = current_user.subscriptions.where(question: @question).first
      gon.current_user = current_user.id
    end
    
    gon.question_id = @question.id
  end

  def new
    @question = Question.new
    @question.links.new
    @question.reward = Reward.new(question: @question)
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Your question successfully deleted.'
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def publish_question
    return if @question.errors.any?
    
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(partial: 'questions/question', locals: { question: @question }))
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                      links_attributes: [:name, :url], reward_attributes: [:name, :image])
  end

end

app/views/questions/_question.html.slim
div class="question-#{question.id}"
  p= link_to question.title, question

app/views/questions/_search_item.html.slim
p
  =link_to resource.title, question_path(resource), target: :_blank

app/views/questions/_subscription_actions.html.slim
.question-subscribtion-actions
  - if can?(:subscribe, @question)
    p = link_to 'subscribe!', question_subscriptions_path(@question), remote: true, method: :post

  - if can?(:unsubscribe, @question)
    p = link_to 'unsubscribe', subscription_path(@subscription), remote: true, method: :delete

app/views/questions/_vote_actions.html.slim
div class="#{vote_class}"
  = link_to '+1', vote_yes_question_path(@question), remote: true, method: :patch
  = " | "
  = link_to '-1', vote_no_question_path(@question), remote: true, method: :patch

app/views/questions/index.html.slim
- cache collection_cache_key_for :question do
  .questions-list
    = render @questions

- if can?(:create, Question)
  p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  
  .reward
    p Reward
    = f.fields_for :reward, @question.reward do |reward|
      p
        = reward.label :name
        = reward.text_field :name
      p
        = reward.label :image
        = reward.file_field :image, direct_upload: true

  = render 'shared/new_links', f: f

  p= f.submit 'Ask'

app/views/questions/show.html.slim
= include_gon

-cache object_cache_key_for(@question, current_user) do
  .question
    .question-errors
      = render 'shared/errors', resource: @question
    
    .question-attributes
      h1= @question.title
      p= @question.body

      = render 'shared/attached', resource: @question
      
      - if @question.reward.present?
        p Reward
        p
          = @question.reward.name
        p
          = link_to @question.reward.image.filename.to_s, url_for(@question.reward.image)

      = render 'shared/links', resource: @question
      .question-rating
        p = "Rating: #{@question.rating}"

    .question-actions
      - if can?(:edit, @question)
        = form_with model: @question, class: 'hidden', html: { id: 'edit-question' } do |f|
          p
            = f.label :title, 'New title'
            = f.text_field :title
          p
            = f.label :body, 'New body'
            = f.text_area :body
          p
            = f.label :files
            = f.file_field :files, multiple: true, direct_upload: true

          = render 'shared/new_links', f: f
          
          p= f.submit 'Save', method: :update

        p
          =link_to 'Edit question', '#', class: 'edit-question-link'
          = " | "
          =link_to 'Delete question', question_path(@question), method: :delete
      
        
      .question-vote-actions
        - if can?(:revote, @question)
          = render 'vote_actions', vote_class: 'question-vote hidden'
          = link_to 're-vote', vote_path(current_user.vote(@question)), class: 'question-re-vote', remote: true, method: :delete
        
        - if can?(:vote, @question)
          = render 'vote_actions', vote_class: 'question-vote'
      
      = render 'subscription_actions'

    
    = render 'shared/comments', resource: @question

    - if can?(:create, Comment)
      = form_with model: [@question, @question.comments.new], class: 'hidden', html: { id: "new-question-comment" } do |f|
        p = f.label :body, 'Comment'
        p = f.text_area :body
        
        p = f.submit

      =link_to 'Add comment', '#', class: 'comment-question-link'
      br = ""

  .answers
    h2 Answers
    = render @question.answers, question: @question

    - if can?(:create, Answer)
      .answer-errors
        = render 'shared/errors', resource: @answer

  - if can?(:create, Answer)
    = render 'answers/form', question: @question, answer: @answer

  = link_to 'Back', questions_path

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if @question.errors.blank? %>
  $('.question-attributes').html('\
    <h1><%= j @question.title %></h1>\
    <p><%= j @question.body %></p>\
    <%= render 'shared/attached', resource: @question %>\
    <%= render 'shared/links', resource: @question %>');

  $('.edit-question-link').show();
  $('form#edit-question').addClass('hidden');

  $('.question-actions #question_files').val('');

  $('.question .field input').each(function(index, item) {
    item.value = '';
  })
<% end %>