config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  concern :votable do
    member do
      patch :vote_yes
      patch :vote_no
    end
  end

  concern :commentable do
    resources :comments, only: [:create]
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, shallow: true, except: :index, concerns: [:votable, :commentable] do
      member do
        patch :mark_as_best
      end
    end

    resources :subscriptions, only: [:create]
  end

  resources :attachments,   only: [:destroy]
  resources :links,         only: [:destroy]
  resources :rewards,       only: [:index]
  resources :votes,         only: [:destroy]
  resources :subscriptions, only: [:destroy]

  resources :authorizations, only: [:create] do
    member do
      get :confirm_email
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, only: [:index, :show, :create, :update, :destroy], shallow: true
      end
    end
  end

  get '/search', to: 'search#search'

  mount ActionCable.server => '/cable'

  root to: 'questions#index'
end

app/views/shared/_attached.html.slim
- if resource.files.attached?
  - resource.files.each do |file|
    p
      = link_to file.filename.to_s, url_for(file)

      - if can?(:destroy, file)
        = ' '
        = link_to 'Delete file', attachment_path(file.id), remote: true, method: :delete

app/views/shared/_comments.html.slim
.comments
  - resource.comments.each do |comment|
    - cache comment do
      p = "\##{comment.user.email}: #{comment.body}"

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name, 'Link name'
    br
    = f.text_field :name
  .field
    = f.label :url
    br
    = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/shared/_links.html.slim
.links
  - if resource.links.count > 0
    p Links:
    ul
      - resource.links.each do |link|
        - if link.gist?
          li
            p
              =link.name
              script src=link.url.delete_suffix('/')+'.js'
              - if can?(:destroy, link)
                = link_to 'Remove link', link_path(link.id), remote: true, method: :delete
        - else
            li
              p
                = link_to link.name, link.url
                - if can?(:destroy, link)
                  = ' '
                  = link_to 'Remove link', link_path(link.id), remote: true, method: :delete

app/views/shared/_new_links.html.slim
.new-links
  p Links:
  p
    = f.fields_for :links do |link|
      = render 'shared/link_fields', f: link
    .links
      = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'