config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  concern :votable do
    member do
      patch :vote_yes
      patch :vote_no
    end
  end

  concern :commentable do
    resources :comments, only: [:create]
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, shallow: true, except: :index, concerns: [:votable, :commentable] do
      member do
        patch :mark_as_best
      end
    end

    resources :subscriptions, only: [:create]
  end

  resources :attachments,   only: [:destroy]
  resources :links,         only: [:destroy]
  resources :rewards,       only: [:index]
  resources :votes,         only: [:destroy]
  resources :subscriptions, only: [:destroy]

  resources :authorizations, only: [:create] do
    member do
      get :confirm_email
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, only: [:index, :show, :create, :update, :destroy], shallow: true
      end
    end
  end

  get '/search', to: 'search#search'

  mount ActionCable.server => '/cable'

  root to: 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user

  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  after_create :notify_question_subscribers

  def best!
    transaction do
      question.answers.update_all(best: false)
      update!(best: true)
      user.rewards << question.reward if question.reward.present? 
    end
  end

  private

  def notify_question_subscribers
    NotificationJob.perform_later(question)
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_answer, only: [:show, :update, :destroy, :mark_as_best]
  before_action :load_question, only: [:new, :create]

  after_action :publish_answer, only: [:create]

  authorize_resource

  skip_authorize_resource :except => [:index, :show, :new, :create, :update, :destroy]
  skip_authorization_check :except => [:index, :show, :new, :create, :update, :destroy]

  def index
  end

  def show
    render partial: 'answers/answer', locals: { answer: @answer }
  end

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def update
    @question = @answer.question
    @answer.update(answer_params)
  end

  def destroy
    @answer.destroy
  end

  def mark_as_best
    authorize! :mark_answer_as_best, @answer

    @question = @answer.question
    @answer.best!

    render 'update'
  end

  private

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def load_question
    @question = Question.find(params[:question_id])
  end

  def publish_answer
    return if @answer.errors.any?
    
    ActionCable.server.broadcast(
      "answers_for_question_#{@answer.question.id}",
      { id: @answer.id,
        user: @answer.user.id,
        author_of_question: @answer.question.user.id,
        html: ApplicationController.render(partial: 'answers/answer_cable', locals: { answer: @answer }) 
      }.to_json )
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url])
  end

end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, only: [:index, :create]
  before_action :load_answer, only: [:show, :update, :destroy]

  authorize_resource

  def index
    render json: @question.answers
  end

  def show
    render json: @answer
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_resource_owner
    
    if @answer.save
      head :ok
    else
      head :unprocessable_entity
    end
  end

  def update
    if @answer.update(answer_params)
      head :ok
    else
      head :unprocessable_entity
    end
  end

  def destroy
    @answer.destroy
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, links_attributes: [:name, :url])
  end
end

app/views/answers/_answer.html.slim
- cache object_cache_key_for(answer, current_user) do
  = "-------------------------------------------"
  div class="answer-#{answer.id}"
    p= answer.body
    = render 'shared/attached', resource: answer
    = render 'shared/links', resource: answer
    
    .answer-rating
      p = "Rating: #{answer.rating}"

    - if can?(:update, answer)
      p
        =link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
        = " | "
        =link_to 'Delete', answer_path(answer), remote: true, method: :delete, class: 'delete-answer-link', data: { answer_id: answer.id }

    - if can?(:mark_answer_as_best, answer)
      =link_to 'Mark as best', mark_as_best_answer_path(answer), remote: true, method: :patch

    - if answer.best?
      | This answer is the best!

    = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
      p
        = f.label :body, 'Your answer'
        = f.text_area :body
      p
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true

      = render 'shared/new_links', f: f
      
      = f.submit 'Save', method: :update

    .answer-vote-actions
      - if can?(:revote, answer)
        = render 'answers/vote_actions', answer: answer, vote_class: "answer-vote hidden"
        = link_to 're-vote', vote_path(current_user.vote(answer)), class: 'answer-re-vote', remote: true, method: :delete, data: { answer_id: answer.id }
        
      - if can?(:vote, answer) 
        = render 'answers/vote_actions', answer: answer, vote_class: "answer-vote"


    = render 'shared/comments', resource: answer

    - if can?(:create, Comment)
      .answer-errors
        = render 'shared/errors', resource: answer

      = form_with model: [answer, Comment.new], class: 'hidden', html: { id: "new-answer-comment-#{answer.id}" } do |f|
        p = f.label :body, 'Comment'
        p = f.text_area :body
        
        p = f.submit

      =link_to 'Add comment', '#', class: 'comment-answer-link', data: { answer_id: answer.id }

app/views/answers/_answer_cable.html.slim
= "-------------------------------------------"
div class="answer-#{answer.id}"
  p= answer.body
  - if answer.files.attached?
    - answer.files.each do |file|
      p
        = link_to file.filename.to_s, url_for(file)

  .links
    - if answer.links.count > 0
      p Links:
      ul
        - answer.links.each do |link|
          - if link.gist?
            li
              p
                =link.name
                script src=link.url.delete_suffix('/')+'.js'
          - else
              li
                p
                  = link_to link.name, link.url

  .answer-rating
    p = "Rating: #{answer.rating}"

  .mark-as-best-link
    =link_to 'Mark as best', mark_as_best_answer_path(answer), remote: true, method: :patch

  - if answer.best?
    | This answer is the best!

  .answer-vote-actions
    = render 'answers/vote_actions', answer: answer, vote_class: "answer-vote"

  = render 'shared/comments', resource: answer

  .answer-errors
    = render 'shared/errors', resource: answer

  .new-answer-comment
    = form_with model: [answer, Comment.new], class: 'hidden', html: { id: "new-answer-comment-#{answer.id}" } do |f|
      p = f.label :body, 'Comment'
      p = f.text_area :body
      
      p = f.submit

    =link_to 'Add comment', '#', class: 'comment-answer-link', data: { answer_id: answer.id }

app/views/answers/_form.html.slim
= form_with model: [@question, @answer], class: 'new-answer', data: { type: :json } do |f|
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  
  = render 'shared/new_links', f: f
  
  = f.submit 'Answer'

app/views/answers/_search_item.html.slim
p
  =link_to resource.body, answer_path(resource), target: :_blank

app/views/answers/_vote_actions.html.slim
div class="#{vote_class}"
  = link_to '+1', vote_yes_answer_path(answer), remote: true, method: :patch, data: { answer_id: answer.id }
  = " | "
  = link_to '-1', vote_no_answer_path(answer), remote: true, method: :patch, data: { answer_id: answer.id }

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
  $('.new-answer #answer_files').val('');

  $('.new-answer .field input').each(function(index, item) {
    item.value = '';
  })
<% end %>

app/views/answers/destroy.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.destroyed? %>
  $('.answer-' + '<%= @answer.id %>').remove();
<% end %>

app/views/answers/new.html.slim
.answer-errors
  = render 'shared/errors', resource: @answer
  
= render 'form'

app/views/answers/show.html.slim
.answer-errors
  = render 'shared/errors', resource: @answer
  
= render 'shared/attached', resource: @answer

- if can?(:destroy, @answer)
  = link_to 'Delete answer', answer_path(@answer), method: :delete

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.errors.blank? %>
  $('.answers').html('<%= j render @question.answers %>');

  $('.answers .field input').each(function(index, item) {
    item.value = '';
  })
<% end %>